[WIP] README Spanish translation
alan-turing-institute/the-turing-way pull request #1338
Opened 2020-09-28 16:59 UTC by camachoreina

### Summary

Fixes #1337 

### List of changes proposed in this PR (pull-request)

* Add a new README.md translated to Spanish: README-Spanish.md

### What should a reviewer concentrate their feedback on?

Reviewer should be Spanish-speaker.

- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

2020-10-02 10:00 UTC, malvikasharan commented
Hi @ChristianECG, I hope you saw that Spanish translation is already happening. You can help review that PR once its ready.

2020-10-05 16:36 UTC, crangelsmith commented
We plan to merge the work @giannidsp from https://github.com/giannidsp/the-turing-way/pull/1/commits to the already translated version.

2020-10-10 13:59 UTC, lauracion requested changes
Hi, 
The translation is very well done! Thank you! I left a few suggestions for changes mostly related to the use of neutral-gender Spanish that is more welcoming for persons of any gender.
I hope this helps.
Best,
Laura

2020-10-10 13:59 UTC, lauracion commented on README-Spanish.md
> +_The Turing Way_ es una guía ligeramente testaruda para la ciencia de datos reproducible.
Sugiero "asertiva" en lugar de "testaruda". Me parece que testaruda tiene una connotación ligeramente más negativa que asertiva.

2020-10-10 13:59 UTC, lauracion commented on README-Spanish.md
> +Actualmente estás en el repositorio de GitHub del proyecto donde se encuentran todos los fragmentos que componen la guía y donde ocurre el proceso de escritura / construcción de la misma.
Sugiero "escritura/construcción" en lugar de "escritura / construcción"

2020-10-10 13:59 UTC, lauracion commented on README-Spanish.md
> +Nuestro objetivo es proporcionar toda la información que los investigadores necesitan al inicio de sus proyectos para garantizar que sean fáciles de reproducir al final.
Sugiero el uso de lenguaje neutro. En lugar de "los investigadores" podría ser "las personas que hacen investigación" o "las y los investigadores", aunque ésta última forma excluye a las personas no binarias.

2020-10-10 13:59 UTC, lauracion commented on README-Spanish.md
> +Esto también significa asegurarse de que los estudiantes de doctorado, los post-doctorantes, los investigadores principales y los equipos de financiación sepan qué partes de la "responsabilidad de re
Sugiero cambiar "asegurarse de que los estudiantes de doctorado, los post-doctorantes, los investigadores principales" por "asegurarse de que estudiantes de doctorado, post-doctorantes, investigadoras e investigadores principales"

2020-10-10 13:59 UTC, lauracion commented on README-Spanish.md
> +- [Acerca el proyecto](#about-the-project)
"Acerca el proyecto" tal vez debería ser "Acerca del proyecto"

2020-10-10 13:59 UTC, lauracion commented on README-Spanish.md
> +Los financiadores y editores científicos están comenzando a exigir que las publicaciones incluyan acceso a los datos subyacentes y al código de análisis.
Sugiero cambiar "Los financiadores y editores científicos" por "Quienes financian y editan trabajos científicos"

2020-10-10 13:59 UTC, lauracion commented on README-Spanish.md
> +Compartir estos resultados de investigación significa comprender la gestión de datos, las bibliotecas, el desarrollo de software y las técnicas de integración continua: habilidades que no se enseñan
Sugiero cambiar "las bibliotecas" por "bibliotecología" que se corresponde mejor con el original "library sciences"

2020-10-10 13:59 UTC, lauracion commented on README-Spanish.md
> +*The Turing Way* es un manual para ayudar a los estudiantes, sus supervisores, financiadores y editores de revistas a garantizar que la ciencia de datos reproducible sea "demasiado fácil como para no
Sugiero cambiar "a los estudiantes, sus supervisores, financiadores y editores de revistas" por "a personas que estudian, supervisan, financian y editan trabajos científicos"

2020-10-10 13:59 UTC, lauracion commented on README-Spanish.md
> +Incluirá material de capacitación sobre control de versiones, *analysis testing* y comunicación abierta y transparente con futuros usuarios, y se basará en los estudios de caso y talleres del Institu
Creo que "analysis testing" puede traducirse como "testeo de análisis". Sugiero cambiar "futuros usuarios" por "futuras personas usuarias".

2020-10-10 13:59 UTC, lauracion commented on README-Spanish.md
> +:construction: Este repositorio es siempre un trabajo en progreso y **todos** están invitados a ayudarnos a construir algo que sea útil para muchos. :construction:
Sugiero cambiar "**todos** están invitados a ayudarnos a construir algo que sea útil para muchos" por "**todas las personas** están invitadas a ayudarnos a construir algo que sea útil para muchas personas"

2020-10-10 13:59 UTC, lauracion commented on README-Spanish.md
> +Se les solicita a quien colaboren con el proyecto que sigan nuestro [código de conducta] (CODE_OF_CONDUCT.md) y que revisen nuestras [pautas de contribución] (CONTRIBUTING.md) para obtener más inform
Sugiero cambiar "Se les solicita a quien colaboren" por "Se le socilita a quienes colaboren"

2020-10-10 13:59 UTC, lauracion commented on README-Spanish.md
> +Si no conoces o tienes dudas de contribuir en GitHub, puedes también contribuir con un estudio de caso y enviarnos consejos a través de nuestro [formulario de envío de Google] (https://goo.gl/forms/a
Sugiero cambiar "tienes dudas de contribuir" a "tienes dudas sobre cómo contribuir"

2020-10-10 13:59 UTC, lauracion commented on README-Spanish.md
> +Hemos utilizado algunas de estas ilustraciones en las respuestas a las contribuciones de nuevos miembros en el [Bot de bienvenida](https://github.com/apps/welcome) de este repositorio de GitHub.
Sugiero cambiar "nuevos miembros" por "personas que se integran a esta comunidad"

2020-10-10 13:59 UTC, lauracion commented on README-Spanish.md
> +También tenemos una lista de correos a las que enviamos actualizaciones mensuales del proyecto. Suscríbete en <https://tinyletter.com/TuringWay>.
"a las que enviamos" -> "a la que enviamos"

2020-10-10 13:59 UTC, lauracion commented on README-Spanish.md
> +Puedes ponerte en contacto con nuestro administrador de la comunidad **Malvika Sharan** por correo electrónico a [msharan@turing.ac.uk](mailto:msharan@turing.ac.uk).
"nuestro administrador" deberia ser "nuestra administradora"

2020-10-10 15:05 UTC, malvikasharan commented
Wonderful! Thank you @lauracion. @camachoreina and @crangelsmith in addition to Laura's review, can I ask you to do the following as well.

- [ ] update your local branch with recent updates from the main branch
- [ ] move your translated file to the folder `README-translated`
- [ ] remove the test-status table. Also, remove contributor's table detail, and instead add a link to the original table (the reason is that we will update this table constantly and would like to avoid duplication)
  - see this file [for example](https://github.com/alan-turing-institute/the-turing-way/blob/master/README-translated/README-Portuguese.md)
- [ ] Add a link to the README-Spanish on the top of Repository's README, for examples "This README.md file in also available in Dutch ([README-Dutch](https://github.com/alan-turing-institute/the-turing-way/blob/master/README-translated/README-Dutch.md)), Portuguese ([README-Portuguese](https://github.com/alan-turing-institute/the-turing-way/blob/master/README-translated/README-Portuguese.md)) and  Spanish ([README-Spanish](https://github.com/alan-turing-institute/the-turing-way/blob/master/README-translated/README-Spanish.md))"

2020-10-10 15:05 UTC, malvikasharan commented
@all-contributors please add @lauracion for translation.

2020-10-14 17:19 UTC, camachoreina commented
Thanks a lot @lauracion for the careful review! Indeed, it is very important to make the test neutral-gender. We had some doubts with some of the sentences and we are glad you helped us resolving those!
All your suggestions were implemented. 
Best,
Reina and Camila

2020-10-14 17:21 UTC, camachoreina commented
Thanks @malvikasharan! All your requests have been implemented. Please take a look and let us know if anything else is missing. Best!

> Wonderful! Thank you @lauracion. @camachoreina and @crangelsmith in addition to Laura's review, can I ask you to do the following as well.
> 
> * [X ]  update your local branch with recent updates from the main branch
> * [X]  move your translated file to the folder `README-translated`
> * [X ]  remove the test-status table. Also, remove contributor's table detail, and instead add a link to the original table (the reason is that we will update this table constantly and would like to avoid duplication)
>   
>   * see this file [for example](https://github.com/alan-turing-institute/the-turing-way/blob/master/README-translated/README-Portuguese.md)
> * [X]  Add a link to the README-Spanish on the top of Repository's README, for examples "This README.md file in also available in Dutch ([README-Dutch](https://github.com/alan-turing-institute/the-turing-way/blob/master/README-translated/README-Dutch.md)), Portuguese ([README-Portuguese](https://github.com/alan-turing-institute/the-turing-way/blob/master/README-translated/README-Portuguese.md)) and  Spanish ([README-Spanish](https://github.com/alan-turing-institute/the-turing-way/blob/master/README-translated/README-Spanish.md))"

2020-10-14 20:57 UTC, malvikasharan commented
Hey @crangelsmith and @camachoreina. the file looks good. So exciting to get this translation added to the project. Muchas gracias <3 please merge it when you are ready!

2020-10-14 20:57 UTC, malvikasharan approved these changes

2020-10-15 10:10 UTC, merged