[WIP] README French translation
alan-turing-institute/the-turing-way pull request #1346
Opened 2020-10-01 12:39 UTC by jessyprovencher

### Summary

Fixes #1337

### List of changes proposed in this PR (pull-request)

* *Add French translation for README.md (see file README-French.md)*

### What should a reviewer concentrate their feedback on?

Reviewer should be French-speaker.

- [ ] Typos / Phrasing
- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

2020-10-22 12:38 UTC, SamGuay commented
:wave:  @jessyprovencher 

Are you still looking for a french-speaking reviewer ? 

Let me know if you want me to review it. 

Thanks

2020-10-25 20:17 UTC, jessyprovencher commented
@SamGuay 

Yes, i'm still looking for a french-speaking reviewer. You can review it anytime! 🎉

2020-10-27 16:33 UTC, malvikasharan commented
@SamGuay I am marking this PR for hacktoberfest accepted to make sure @jessyprovencher gets to count this towards his 4 PR :), while I let you review it in your time.

2020-11-09 13:17 UTC, KirstieJane commented
Hi @jessyprovencher ! @SamGuay and I are just having a look at this PR now - I wonder if you could make sure that you're up to date with master? It feels like there are a lot of commits in this branch that shouldn't be showing up 😕 I think maybe its GitHub being a little strange. Ping me if you aren't sure how to do that though!

2020-11-09 13:33 UTC, SamGuay commented on README-French.md
> +
```suggestion
<!-- ALL-CONTRIBUTORS-BADGE:START - Do not remove or modify this section -->
[![Tous les contributeurs et contributrices](https://img.shields.io/badge/tous_les_contributeurs_et_contributrices-206-orange.svg)](#contributors)
<!-- ALL-CONTRIBUTORS-BADGE:END -->
```

2020-11-09 16:06 UTC, jessyprovencher commented
> 
> 
> Hi @jessyprovencher ! @SamGuay and I are just having a look at this PR now - I wonder if you could make sure that you're up to date with master? It feels like there are a lot of commits in this branch that shouldn't be showing up 😕 I think maybe its GitHub being a little strange. Ping me if you aren't sure how to do that though!

I tried a few weeks ago to update with master branch but look like i've made a mistake... (not quite skilled with large Git repos) I'd like some help to clear those up and update with the changes made. Hope to hear from you soon! 🎉

2020-11-09 16:17 UTC, SamGuay commented
I'll leave the cleaning part to @KirstieJane. 

As for the review, I'll probably be able to finish it by tomorrow or by wednesday. I'm working on it for the The Turing Way | Book Dash November 2020 before diving into finding the best inclusive writing guide! I'll make a couple of suggestions and if my suggestions are not clear enough or you think we should improve more, we can always have a chat. Overall, it seems pretty good, so there should be much to do! 

Thanks again for your contribution :muscle:

2020-11-10 14:01 UTC, SamGuay requested changes
Here are my suggestions. Feel free to adapt them as you see fit.

2020-11-10 19:01 UTC, jessyprovencher commented on README-French.md
> +Vous consultez actuellement le dépôt GitHub du projet où tous les éléments qui composent le guide sont en ligne et où se déroule le processus d'écriture / de construction du guide.
```suggestion
Vous consultez actuellement le dépôt GitHub du projet dans lequel se trouve tous les éléments qui composent le guide et ses processus d'écriture / de construction.
```

2020-11-13 15:48 UTC, SamGuay approved these changes
All is good now.

2020-11-13 16:05 UTC, closed without merging

2020-11-13 16:12 UTC, KirstieJane commented
Hi folks!! I've accidentally done something super wild and accidentally lost @jessyprovencher's changes in HIS fork of the repository. BAD KIRSTIE.

However, I had made a different error earlier and had pushed the changes to a branch in this repository. That PR is open now at #1590.

My suggestion is that we keep this PR closed, and we merge #1590 if all the changes are ready to go.

Many apologies for my wild git-ing 🙈  and thank you SO MUCH for this fantastic work!