Retrospective Consistency on RDM chapter of Guide to Reproducible Research
alan-turing-institute/the-turing-way pull request #1463
Opened 2020-10-22 04:11 UTC by paulowoicho

### Summary

Partially Fixes #1174, moved from #1396

This PR addresses some of the consistency issues highlighted in issue 1174 for the Research Data Management chapter of the Guide to Reproducible Research. (This branch is up to date with my master branch, so it carries those changes as well)

### List of changes proposed in this PR (pull-request)

* Ensuring the names of chapters/subchapters map exactly to the left TOC.
* Ensuring consistency with the Turing Way Style Guide
* Ensuring correct grammar and a consistent tone (with the help of Grammarly)
* Making chapters, subchapters, and sections of the book 'reference-able' by adding labels.
* Converting all HTML formatting to markdown, where possible
* Ensuring proper title casing for headers
* Ensuring chapters follow the structure discussed in #1174 

### What should a reviewer concentrate their feedback on?

- [ ] Do the changes make sense and does everything look ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

2020-10-27 16:29 UTC, malvikasharan commented
I have tagged @EstherPlomp and @Ismael-KG to review this, whoever has some time and can check your contribution.

2020-10-27 19:41 UTC, EstherPlomp requested changes
Hi @paulowoicho. Thanks so much for all of that! I only have some minor suggestions for change before merging.

2020-10-27 19:41 UTC, EstherPlomp commented on book/website/reproducible-research/rdm/rdm-spreadsheets.md
> +Use a README file and other design choices to explain naming conventions.
to explain naming convention _and other structure choices._

2020-10-27 19:41 UTC, EstherPlomp commented on book/website/reproducible-research/rdm/rdm-spreadsheets.md
> +It will make it clear to others what the header names mean and what criteria to consider when designing an analysis workflow.
what the _file and_ header names mean

2020-10-27 23:10 UTC, paulowoicho commented on book/website/reproducible-research/rdm/rdm-stories.md
> +Formerly seen as an intersection between service provision and IT, data management has become a first-class citizen, recognized as a research and development subject, as it should be.
It's British spelling! I must have changed my Grammarly settings at this point

2020-10-27 23:10 UTC, paulowoicho commented on book/website/reproducible-research/rdm/rdm-stories.md
> +Formerly seen as an intersection between service provision and IT, data management has become a first-class citizen, recognized as a research and development subject, as it should be.
```suggestion
Formerly seen as an intersection between service provision and IT, data management has become a first-class citizen, recognised as a research and development subject, as it should be.
```

2020-10-27 23:58 UTC, paulowoicho commented
Thank you @EstherPlomp for the review! I have made the edits you suggested

2020-10-28 14:54 UTC, EstherPlomp approved these changes
Great, no further comments from my side! Cheers! :)

2020-10-29 20:37 UTC, merged