Deletes a duplicated sentence in Docker section
alan-turing-institute/the-turing-way pull request #2168
Opened 2021-11-09 16:25 UTC by pc494

Assumed to be a typo, couldn't see sensible context for it otherwise.

### Summary

I couldn't find an open issue or PR for this, and it seemed like a good first PR to raise.

### List of changes proposed in this PR (pull-request)

* [x] Deletes a duplicated sentence

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file: @pc494

2021-11-09 17:24 UTC, Arielle-Bennett approved these changes
Looks OK - agree that it appears to be a duplicated sentence.

2021-11-09 18:41 UTC, da5nsy requested changes

2021-11-09 18:41 UTC, da5nsy commented on book/website/reproducible-research/renv/renv-containers.md
>  Say a container is opened, and work is done within it. If that container is closed, and the image it came from is again used to start another container, none of that work will be in the new one.
```suggestion
Say a container is opened, and work is done within it. 
If that container is closed, and the image it came from is again used to start another container, none of that work will be in the new one.
```
Adding a semantic line break (as per [here](https://the-turing-way.netlify.app/community-handbook/style.html#write-each-sentence-in-a-new-line-line-breaks))

2021-11-09 18:42 UTC, da5nsy approved these changes

2021-11-09 18:45 UTC, da5nsy commented
Thanks @pc494! 
I added a semantic line break (as per [here](https://the-turing-way.netlify.app/community-handbook/style.html#write-each-sentence-in-a-new-line-line-breaks)). Otherwise, all LGTM so I'll merge!

@all-contributors please add @pc494 for bug

2021-11-09 18:46 UTC, merged

2021-11-10 08:20 UTC, pc494 commented
> Thanks @pc494! I added a semantic line break (as per [here](https://the-turing-way.netlify.app/community-handbook/style.html#write-each-sentence-in-a-new-line-line-breaks)). Otherwise, all LGTM so I'll merge!
> 
> @all-contributors please add @pc494 for bug

Thank you, sorry for the error there.