Iramosp patch 1
alan-turing-institute/the-turing-way pull request #2557
Opened 2022-08-10 15:09 UTC by iramosp

### Summary

Add my name to the CarpentryCon Workshop

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

2022-08-10 16:13 UTC, BrainonSilicon requested changes
The latest commit will be accepted but the others needs to stay in the fork. 

The easiest way to fix this on our end will be to: create a branch from the remote HEAD, cherry-pick the commit to that branch, push the branch to your repo on GitHub, then create a pull request.

```
git checkout -b mybranch
git fetch upstream
git reset --hard upstream/master
git cherry-pick <commit-hash>
git push origin mybranch:mybranch
```

2022-08-17 10:15 UTC, aleesteele approved these changes

2022-08-17 10:16 UTC, aleesteele commented
Looks great @iramosp 🚀 

@all-contributors please add @iramosp for bugs

2022-08-17 10:16 UTC, aleesteele approved these changes

2023-03-22 11:45 UTC, closed without merging