Lint and validate YAML files in CI
alan-turing-institute/the-turing-way pull request #2732
Opened 2022-10-14 13:37 UTC by sgibson91

### Summary

Fixes #<NUM>

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

### List of changes proposed in this PR (pull-request)

* *Lorem ipsum dolor sit amet, consectetur adipiscing.*
* *Lorem ipsum dolor sit amet, consectetur adipiscing.*

### What should a reviewer concentrate their feedback on?

- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file:

2022-10-14 16:26 UTC, aleesteele commented
Tagging @JimMadge and @da5nsy here, in case you have time to review! 🙏

2022-10-15 07:02 UTC, JimMadge requested changes
LGTM :+1:

There are a few references to 'master', the old default branch name, in the GitHub workflow files so it might be worth updating those while we are looking.

2022-10-15 07:02 UTC, JimMadge commented on .github/workflows/lorem-ipsums.yml
> +      - name: Run Python script to check for rogue "Lorem ipsums" - Master
```suggestion
      - name: Run Python script to check for rogue "Lorem ipsums" - Main branch
```

2022-10-15 07:02 UTC, JimMadge commented on .github/workflows/no-bad-latin.yml
> +      - name: Run Python script to check for latin phrases - Master
```suggestion
      - name: Run Python script to check for latin phrases - Main branch
```

2022-10-15 07:03 UTC, JimMadge approved these changes

2022-10-15 22:49 UTC, da5nsy approved these changes
COOL! LGTM

2022-10-17 09:59 UTC, aleesteele approved these changes

2022-10-17 14:50 UTC, merged