Update Localization Guidelines
alan-turing-institute/the-turing-way pull request #3153
Opened 2023-05-26 11:25 UTC by BatoolMM

### Summary

This PR adds pointers to the localization guidelines in the README and welcome page, along with updates to certain instructions in the guide. 

Fixes #2961 

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

### List of changes proposed in this PR (pull-request)

- [ ] Added links to the localization guidelines in the README
- [ ] Added links to the localization guidelines in the welcome page
- [ ] Relocated the localization chapter 
- [ ] Updated instructions for our localization co-working meetings

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file:

2023-05-26 11:52 UTC, BatoolMM commented
The CI is failing because of a problem with reference `datastudygrouproche2020 ` which is getting fixed in #3150

2023-05-26 16:45 UTC, da5nsy commented on book/website/community-handbook/translation/translation-workflow.md
>  You will also have to create a Crowdin account but more on that [in the next section](#ch-translation-getting-started).
```suggestion
You will also have to create a Crowdin account but more on that [in the next section](#ch-translation-localisation-journey).
```
Looks like this chapter was renamed?

2023-05-26 17:48 UTC, da5nsy commented
This should now pass CI once the chapter title is updated - https://github.com/alan-turing-institute/the-turing-way/pull/3153#discussion_r1207063348 😄

2023-05-28 12:50 UTC, da5nsy requested changes

2023-05-28 12:50 UTC, da5nsy commented on book/website/community-handbook/translation/translation-workflow.md
> +You will also have to create a Crowdin account but more on that [in the next section](#ch-translation-localisation-journey).
```suggestion
You will also have to create a Crowdin account but more on that {ref}`in the next section<ch-translation-localisation-journey>`
```

2023-05-28 12:50 UTC, da5nsy commented on book/website/community-handbook/translation/translation-workflow.md
> +Everyone interested in participating in a translation effort should be able to work asynchronously, so don't worry if you cannot join the bi-weekly calls. More info can be found in the next chapter a
```suggestion
Everyone interested in participating in a translation effort should be able to work asynchronously, so don't worry if you cannot join the fortnightly calls. More info can be found in the next chapter about {ref}`our localisation workflow<ch-translation-localisation-journey>`.
```

2023-05-28 12:50 UTC, da5nsy commented on book/website/community-handbook/translation/translation-workflow.md
> +We have also set up a public page for _The Turing Way_ in [Crowdin](https://turingway.crowdin.com/turing-way) with a README file summarising some of the translation guidelines. Make sure you read the
```suggestion
We have also set up a public page for _The Turing Way_ in [Crowdin](https://turingway.crowdin.com/turing-way) with a README file summarising some of the translation guidelines. 
Make sure you read these guidelines before you start translating for the first time.
```
https://the-turing-way.netlify.app/community-handbook/style.html#write-each-sentence-in-a-new-line-line-breaks

2023-05-28 12:50 UTC, da5nsy commented on book/website/community-handbook/translation/translation-workflow.md
> +Check out our [guidelines](ch-translation-localisation-journey) for a list of the priority list.
```suggestion
Check out our {ref}`guidelines<ch-translation-localisation-journey>` for a list of the priority list.
```

2023-05-28 12:50 UTC, da5nsy commented on book/website/index.md
> +Call for translators! We’re looking for translators to help translate this space for everyone! Read more about our translation workflow and how you can contribute to it [here](https://the-turing-way.
```suggestion
Call for translators! We’re looking for translators to help translate this space for everyone! Read more about our translation workflow and how you can contribute to it {ref}`here<ch-translation>`.
```

2023-05-28 12:50 UTC, da5nsy commented on book/website/index.md
> +
```suggestion
```

2023-05-28 20:18 UTC, da5nsy approved these changes

2023-06-06 13:52 UTC, AndreaSanchezTapia commented
Hi @da5nsy I'll review it and let you know when it's done. Thanks!

2023-06-14 15:06 UTC, BatoolMM commented
Thank you @da5nsy and @AndreaSanchezTapia!

2023-06-20 17:06 UTC, melibleq approved these changes
I only made a couple suggestions for the content in [book/website/index.md](https://github.com/alan-turing-institute/the-turing-way/pull/3153/files#diff-669d774a1fe68422fb6a4a569ff95b7d51a8e8d358dcbcc5c4d1443d75a2e8cd). Checked links in the deployed version to see if they're pointing to the correct pages and it all looks good to me!

2023-06-20 17:08 UTC, melibleq commented on book/website/index.md
> +Call for translators! We’re looking for translators to help translate this space for everyone! Read more about our translation workflow and how you can contribute to it {ref}`here<ch-translation>`.
The second substitution (from "here" to in the "translation chapter") was to follow accessibility guidelines. I think it's more recommended to actually say what the link is about than to call it "here".

2023-07-03 10:17 UTC, BatoolMM commented
Thank you @melibleq @AndreaSanchezTapia and @da5nsy for the review 🌷 
@da5nsy would you mind rebasing the PR if needed and merging it, when you have time, pls?

2023-07-03 12:34 UTC, merged