Upload illustrations from the May Book Dash
alan-turing-institute/the-turing-way pull request #3234
Opened 2023-07-20 15:09 UTC by malvikasharan

### Summary

Addresses an action #2301 

* Uploading images in reduced size, original images on Zenodo: https://zenodo.org/record/8169292

### List of changes proposed in this PR (pull-request)

* Uploaded images with text in smaller sizes

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file:

2023-07-20 15:10 UTC, malvikasharan commented
Alt text are being collected here: https://docs.google.com/spreadsheets/d/1B4mm-7ELWZCkHqE2rfeML1z803TNSnjLReMTlvyEltQ/edit#gid=0

2023-07-20 16:03 UTC, jcolomb requested changes
should we wait to have the alt text ?

2 exists in 2 versions, either comment or delete one version.

2023-07-20 16:03 UTC, jcolomb commented on book/website/figures/multi-tasking-community-manager.jpg
this one has no text, should it be added anyway?

2023-07-20 16:03 UTC, jcolomb commented on book/website/figures/five-year-partnership.jpg
also a second version with TTW and Roche mentioned is below, should both be uploaded ?

2023-07-20 18:03 UTC, malvikasharan commented on book/website/figures/multi-tasking-community-manager.jpg
ah probably not.

2023-07-20 18:03 UTC, malvikasharan commented on book/website/figures/five-year-partnership.jpg
Vicky will be using the one with logo in her case study, may be the one without text is not needed.

2023-07-20 18:11 UTC, malvikasharan commented on book/website/figures/multi-tasking-community-manager.jpg
Removed it.

2023-07-20 18:14 UTC, malvikasharan commented
> should we wait to have the alt text ?

we can publish it, as the alt text will be used only in the chapters. We are also having a separate discussion on having a centralised location for all alt text, but this PR is not a blocker for that.

> 2 exists in 2 versions, either comment or delete one version.

I have removed the unlabeled community manager image. I will wait to hear from Vicky about the image she would like to keep for her chapter on academia-industry partnership.

Thank you for the prompt review Julien! 🥇

2023-07-20 18:21 UTC, vhellon commented on book/website/figures/five-year-partnership.jpg
Yes I will use the one with text please as it gives context for the research themes that are illustrated

2023-07-23 18:51 UTC, da5nsy reviewed
I'm assuming SVGs are not available?

If higher-quality bitmap versions exist that have not been jpeg compressed already, I'm happy to do my compression tricks (convert to png with indexed color)[1] to get better compression rates and higher image quality.

If not, LGTM!

[1]: _I really need to work out how to automate that..._ (throwback backlink: https://github.com/alan-turing-institute/the-turing-way/pull/2251#issuecomment-1219564091)

2023-08-02 08:36 UTC, jcolomb commented
can we merge this now? waiting for the image for finishing #3111

2023-08-02 08:51 UTC, jcolomb requested changes

2023-08-02 08:51 UTC, jcolomb commented on book/website/figures/scientific-assessment.jpg
can we rename this file: "why-open-hardware.jpg"

2023-08-07 13:32 UTC, jcolomb approved these changes
all good now

2023-08-08 07:46 UTC, merged